### ISSUE TITLE
Kubernetes tips

### ISSUE THREAD

**Issue by opskumu** [opskumu/issues#10]
- `kubectl get`

```
   * clusters (valid only for federation apiservers)
   * componentstatuses (aka 'cs')
   * configmaps (aka 'cm')
   * daemonsets (aka 'ds')
   * deployments (aka 'deploy')
   * events (aka 'ev')
   * endpoints (aka 'ep')
   * horizontalpodautoscalers (aka 'hpa')
   * ingress (aka 'ing')
   * jobs
   * limitranges (aka 'limits')
   * nodes (aka 'no')
   * namespaces (aka 'ns')
   * petsets (alpha feature, may be unstable)
   * pods (aka 'po')
   * persistentvolumes (aka 'pv')
   * persistentvolumeclaims (aka 'pvc')
   * quota
   * resourcequotas (aka 'quota')
   * replicasets (aka 'rs')
   * replicationcontrollers (aka 'rc')
   * secrets
   * serviceaccounts (aka 'sa')
   * services (aka 'svc')
```

**Comment by opskumu** [comment]
技术文章：

* [细数Kubernetes Service那些事－kubernetes 服务发布以及在eBay的实践](http://blog.csdn.net/ebay/article/details/52798074)

**Comment by opskumu** [comment]
* 当前 `namespace` 切换

```
# kubectl config set-context test --namespace=test
context "test" set.
# kubectl config use-context test
switched to context "test".
# kubectl get pods
NAME          READY     STATUS    RESTARTS   AGE
nginx-783ko   1/1       Running   2          24m
# kubectl config current-context
test
# kubectl config view
apiVersion: v1
clusters: []
contexts:
- context:
    cluster: ""
    namespace: test
    user: ""
  name: test
current-context: test
kind: Config
preferences: {}
users: []
```

> more help: `kubectl config --help`

**Comment by opskumu** [comment]
## Grafana + Prometheus

* Grafana Dashboard 模板:
    * [Kubernetes cluster monitoring (via Prometheus)](https://grafana.net/dashboards/315)
* Prometheus Configure

```
      scrape_configs:
        - job_name: kubernetes-nodes
          scrape_interval: 10s
          scrape_timeout: 10s
          scheme: http  # remove if you want to scrape metrics on insecure port
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecure_skip_verify: true
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          kubernetes_sd_configs:
          - role: node
          relabel_configs:
          - source_labels: [__address__]
            regex: '(.*):10250'
            replacement: '${1}:10255'
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          metric_relabel_configs:
          - action: replace
            source_labels: [id]
            regex: '^/machine\.slice/machine-rkt\\x2d([^\\]+)\\.+/([^/]+)\.service$'
            target_label: rkt_container_name
            replacement: '${2}-${1}'
          - action: replace
            source_labels: [id]
            regex: '^/system\.slice/(.+)\.service$'
            target_label: systemd_service_name
            replacement: '${1}'
```

**Comment by opskumu** [comment]
## 坑

* client-go `QPS` & `Burst`

默认 Kubernetes client-go `QPS` 和 `Burst` 值较小：

```
k8s.io/client-go/1.4/rest/config.go:    DefaultQPS   float32 = 5.0
k8s.io/client-go/1.4/rest/config.go:    DefaultBurst int     = 10
k8s.io/client-go/1.4/rest/config.go:    // If it's zero, the created RESTClient will use DefaultQPS: 5
k8s.io/client-go/1.4/rest/config.go:    // If it's zero, the created RESTClient will use DefaultBurst: 10.
```

并发请求时性能会很差，可根据实际情况修改这两个默认值。

**Comment by opskumu** [comment]
## Defining readiness probes

Sometimes, applications are temporarily unable to serve traffic. For example, an application might need to load large data or configuration files during startup. In such cases, you don’t want to kill the application, but you don’t want to send it requests either. Kubernetes provides readiness probes to detect and mitigate these situations. A pod with containers reporting that they are not ready does not receive traffic through Kubernetes Services.

Readiness probes are configured similarly to liveness probes. The only difference is that you use the readinessProbe field instead of the livenessProbe field.

```
readinessProbe:
  exec:
    command:
    - cat
    - /tmp/healthy
  initialDelaySeconds: 5
  periodSeconds: 5
```

Configuration for HTTP and TCP readiness probes also remains identical to liveness probes.

Readiness and liveness probes can be used in parallel for the same container. Using both can ensure that traffic does not reach a container that is not ready for it, and that containers are restarted when they fail.

**Comment by opskumu** [comment]
## GPU with K8s

> [How to automate deep learning training with Kubernetes GPU-cluster](https://github.com/Langhalsdino/Kubernetes-GPU-Guide) 可以看这篇文章入门

当前 K8s 调度 GPU 还是实验性阶段，在 K8s 调度 GPU 之前需要提前做好以下几步：

* 1、安装 Nvidia 驱动
* 2、kubelete 添加 `-feature-gates="Accelerators=true"` 选项
* 3、必须是 `docker engine` 运行环境

K2 后续会支持 GPU 调度，当前 GPU 主机少，没有必要进行相关调度。这里只介绍原生 K8s 调用方式：

```
apiVersion: v1
kind: pod
spec: 
  containers: 
      name: gpu-container-1
      resources: 
        limits: 
          alpha.kubernetes.io/nvidia-gpu: 2 # requesting 2 GPUs
```

有几点问题需要注意：

* GPUs 只能通过 `limits` 选项指定
* GPUs 是严格隔离的，不同容器之间不用共享
* 每个容器可以请求一个或多个 GPUs
* GPUs 只能正整数级请求
