### ISSUE TITLE
学习周报「2020」

### ISSUE THREAD

**Issue by opskumu** [opskumu/issues#26]
### [学习周报「2019」](https://github.com/opskumu/issues/issues/23) #23

**Comment by opskumu** [comment]
## 2019-01-01~05

### etcd OOM 问题

线上 etcd 偶尔会出现 OOM 的情况，查看 tcp 连接发现有大量的连接没有释放 15w+ ，这个是极不正常的数据：

```
# ss -s
Total: 152111 (kernel 152263)
TCP:   152797 (estab 152025, closed 751, orphaned 0, synrecv 0, timewait 748/0), ports 54679

Transport Total     IP        IPv6
*         152263    -         -
RAW       0         0         0
UDP       6         5         1
TCP       152046    151908    138
INET      152052    151913    139
FRAG      0         0         0
```

排查出连接客户端集中在某一个业务，应该和 [记一次ETCD OOM问题排查](https://www.jianshu.com/p/05486908814d) 相关，关于如何关闭 etcd watcher 可以访问文中提到的 [如何结束 etcd watcher](http://holys.im/2016/10/19/how-to-stop-etcd-watcher/)

**Comment by opskumu** [comment]
## 2019-01-06~12

### kubectl rollout pause/resume

之前觉得 pause 和 resume 的功能比较鸡肋，用处不是很大，Deployment pause 也不能按照比例控制 Pod 更新，最近用 pause 的时候感觉有些场景还是比较适用的，比如要修改多个配置项的时候，先 pause 一下，修改完毕之后再 resume，在这种变更场景下，感觉 pause 和 resume 还是很有用的。

**Comment by opskumu** [comment]
## 2019-01-13~19

**Comment by opskumu** [comment]
## 2020-02-03~09

**Comment by opskumu** [comment]
## 2020-02-10~16

**Comment by opskumu** [comment]
## 2020-02-24~29

### Harbor 安装和升级标注

> 安装统一下载在线安装包，离线安装包比较大，因为集成了离线镜像，意义不大 https://github.com/goharbor/harbor/releases

#### 1.5.x

##### 目录结构

```
# tree -L 1 harbor
harbor
├── common                          # 配置目录
├── docker-compose.clair.yml        # clair 编排文件
├── docker-compose.notary.yml       # notary 编排文件
├── docker-compose.yml              # 编排文件
├── ha                              # ha 配置目录
├── harbor.cfg                      # 配置文件
├── install.sh                      # 安装脚本
├── LICENSE
├── NOTICE
├── open_source_license
└── prepare                         # 环境初始化脚本

2 directories, 9 files
```

#### 环境和配置初始化

`harbor.cfg` 为配置文件，根据实际需求修改。`common` 下为相关组件的模板文件，`prepare` 脚本会根据 `harbor.cfg` 和 `common` 下的模板文件生成实际的配置文件。`install.sh` 会调用 `prepare` 并启动 harbor。因此正常情况下我们只需要修改 `harbor.cfg` 并执行 `install.sh` 即可。不过实际生产环境使用过程中一般会有一些自定义的需求，比如一般会把 MySQL 单独抽离，使用现成的服务，还不是默认 compose 文件中启动的。 接下来会详细介绍一下，首先修改 `harbor.cfg`，然后执行 `prepare`，`harbor.cfg` 相对易懂，这里不展开讲：

```
# ./prepare
Generated and saved secret to file: /data/secretkey
Generated configuration file: ./common/config/nginx/nginx.conf
Generated configuration file: ./common/config/adminserver/env
Generated configuration file: ./common/config/ui/env
Generated configuration file: ./common/config/registry/config.yml
Generated configuration file: ./common/config/db/env
Generated configuration file: ./common/config/jobservice/env
Generated configuration file: ./common/config/jobservice/config.yml
Generated configuration file: ./common/config/log/logrotate.conf
Generated configuration file: ./common/config/jobservice/config.yml
Generated configuration file: ./common/config/ui/app.conf
Generated certificate, key file: ./common/config/ui/private_key.pem, cert file: ./common/config/registry/root.crt
The configuration files are ready, please use docker-compose to start the service.
```

可以从输出看出 `prepare` 脚本主要是用来生成证书、配置文件等。

> 如果开启 https，则需要提前创建相关证书，可参考 https://github.com/goharbor/harbor/blob/v1.5.2/docs/configure_https.md

`harbor.cfg` 定义了 `db_host`、`db_password`、`db_port` 以及 `db_user` 唯独没有定义库名，这里模板 `common/templates/adminserver/env` 中是固定死的，为 `MYSQL_DATABASE=registry`。如果你使用外部的数据库，那么你需要根据实际的库名修改此处。 

使用外部的数据库需要提前导入相关的表，相关 SQL 文件安装包并没有提供，需要下载 `vmware/harbor-db:v1.5.2` 镜像，SQL 文件位置为 `/docker-entrypoint-initdb.d/registry.sql` 拷贝出来，导入数据库即可。在执行相关操作的时候，还需要额外修改 `docker-compose.yml` 文件，去除 harbor-db 的依赖，然后再执行 `docker-compose up -d` 启动 harbor 服务。当然，也可以直接执行 `install.sh` 一步到位，这里拆开来说是方便了解整个过程。

#### 升级 1.5.x -> 1.6.x 

因为 1.6.0  版本开始数据库从 MariaDB 变更到 Postgresql，1.5.x 的版本如果往上升级则需要先升级到 1.6.x 版本，在此基础上进行后续的升级。

关闭和备份旧版本

```
docker-compose down
mv harbor harbor_bak
```

备份数据和配置（更新到什么版本，下载具体 tag 的迁移镜像，如此处升级到 1.6.3 则迁移镜像为 `goharbor/harbor-migrator:v1.6.3`）

```
docker run -it --rm -e DB_USR=root -e DB_PWD=<数据库密码> -v <旧版本数据存储目录>:/var/lib/mysql -v <旧版本配置路径>:/harbor-migration/harbor-cfg/harbor.cfg -v <备份目录>:/harbor-migration/backup goharbor/harbor-migrator:[tag] backup
```

数据和配置升级，在 1.5.x 升级到 1.6.x 时候，因为涉及到 DB 的变更，这步操作会把原始数据目录的格式转为 PostgreSQL，此处要注意，每次升级前都要执行上面的备份操作。

```
docker run -it --rm -e DB_USR=root -e DB_PWD=<数据库密码> -v <旧版本数据存储目录>:/var/lib/mysql -v <旧版本配置路径>:/harbor-migration/harbor-cfg/harbor.cfg goharbor/harbor-migrator:[tag] up
```

把新版本解压到原始程序目录 harbor 中，然后使用上面的更新过的配置替换当前的配置，执行 `./install.sh` 即可启动新版本的服务，当然如果涉及到外部的数据库，操作同之前的。

> https://github.com/goharbor/harbor/blob/v1.6.3/docs/migration_guide.md

####  升级 1.6.x -> 1.8.x

因为版本限制，如果要升级到 1.10.x 需要先升级到 1.7.x，这里直接跳过升级到 1.8.x（当然升级到 1.7.x 再升级到 1.10.x 也是可以的）。后续的 Harbor 版本安装对 Docker 版本有要求了，所以建议升级 Docker 版本到最新版本。

```
docker-compose down
mv harbor harbor_bak
cp -r /data/database /my_backup_dir/
tar xf harbor-online-installer-v1.8.6.tgz 
```

更新配置

```
docker run -it --rm -v <旧版本配置路径>:/harbor-migration/harbor-cfg/harbor.yml -v <新版本 harbor.yml 配置路径>:/harbor-migration/harbor-cfg-out/harbor.yml goharbor/harbor-migrator:[tag] --cfg up
```

安装启动

`./install.sh --with-chartmuseum` 执行安装指令，这里还额外支持 Helm Charts。

> https://github.com/goharbor/harbor/blob/v1.8.6/docs/migration_guide.md

**Comment by opskumu** [comment]
## 2020-03-02~03-08

**Comment by opskumu** [comment]
## 2020-03-09~15

### Harbor Helm charts

+ Add Harbor as a unified single index entry point

```
helm repo add --ca-file ca.crt --username=admin --password=Passw0rd myrepo https://xx.xx.xx.xx/chartrepo
```

+ Add Harbor project as separate index entry point

```
helm repo add --ca-file ca.crt --username=admin --password=Passw0rd myrepo https://xx.xx.xx.xx/chartrepo/myproject
```

> https://github.com/goharbor/harbor/blob/v1.9.4/docs/user_guide.md

**Comment by opskumu** [comment]
## 2020-03-16~22

**Comment by opskumu** [comment]
## 2020-03-30~04-05

**Comment by opskumu** [comment]
## 2020-04-06~12

### 关于 Pod 莫名 TaintManagerEviction 的问题

今天同事反馈某开发测试节点上部署的服务总是隔几分钟被删除，然后重新创建。事件信息显示如下：

```
LAST SEEN   TYPE     REASON                 KIND          MESSAGE
2m23s       Normal   TaintManagerEviction   Pod           Cancelling deletion of Pod default/zk-0
```

想了下好像很久以前测试的时候给该节点加过 taint，一看果然....

```
taints:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
```

自 1.13 开始，Pod 会默认启用以下 tolerations，默认时间是 300s，这也就是为什么这个节点上的对应 Pod 每隔一段时间会被干掉.....

```
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
```

然后转念一想，好像好久之前自己测试 zk Operator 的时候也遇到这个问题了，当时以为是 zk Operator 本身的问题，一度对 Operator 怀有敌意，然后今天才发现自己当时被自己给坑了...... 

ಥ_ಥ 这是个悲伤的故事

**Comment by opskumu** [comment]
## 2020-04-13~19

### 小规模应用 docker 交付方案

去年的时候调研了一下小规模 docker 交付方案，想了下用 docker 自带的体系就可以，足够轻量级， 如 docker-compose yaml + docker stack + docker swarm + portainer。最近刚好在做交付的事情，在这个基础下又简化一下，直接使用 docker-compose yaml  管理，复杂一点场景再结合 ansible。这种方案基本也能解决大部分问题，主要是足够简单。

**Comment by opskumu** [comment]
## 2020-04-20~26

**Comment by opskumu** [comment]
## 2020-04-27~05-03

### 关于 K8s  CephFS 存储挂载一次权限问题的解决方法

#### 问题描述：

由于某种特殊的需求，内部办公网有 3 个服务器通过专线连接机房网络，并作为节点加入到了线上 K8s 集群，这几个节点的 Pod 还会挂载线上 Cephfs 存储。因为一些原因需要进行网络割接，同机房连接切换为备的 VPN 方式。这时候 Ceph 连接出现了诡异的情况，重连之后，有两个节点的 Pod 中挂载的 Cephfs 目录访问显示 `Permission denied`，其中一台并没有问题。客户端内核错误显示如下：

![image](https://user-images.githubusercontent.com/5445356/80442027-af490f80-893e-11ea-91be-8853ceac018f.png)

#### 问题排查和解决：

Ceph Server 端查看日志信息，客户端查看 Kernel 信息，没有特别有效的信息，实际在问题节点上挂载测试，挂载是成功的，但是访问也是报 `Permission denied`，但是在其他主机同样的账户和 secret 是可以连接正常的。

期间操作，在问题描述中已经说明，除了网络变更没有任何的其他变更。因为生产机房也有同样的 Cephfs 挂载，并没有办公网这几台节点的问题，而且三个节点只有两个节点发生这个问题。

怀疑是重连过程中导致的偶发问题，尝试通过 `tcpkill` 与 Ceph 的连接端口，让它自动重建，经过几次测试发现还是报同样的错误。

两个节点，其中一个节点的 Pod 是不能重启的（Ceph 写入问题不影响服务业务本身，会影响数据落盘），尝试驱逐另外一个可以操作的节点 Pod，再加入调度，发现 Ceph 正常连接了......

确认重新创建是可以解决问题的，但是另外一个节点的 Pod 是不能中断的。忽然想到使用其他账户挂载测试看看，居然挂载成功，而原有账号在其他正常节点连接又没有问题。于是有了接下来的解决方案，手动卸载容器中挂载的 Cephfs，再手动用其他账户挂载上去，先保证服务本身可用。

如果要操作 `mount` 和 `unmount` 在容器中没有赋权是操作不了的，所以需要通过 `nsenter` 进入对应 namespace 操作：

```
docker inspect --format "{{.State.Pid}}" <Container_ID>  // 获取容器 PID
nsenter -m -u -i -n -p -t <Container_PID>                // 进入对应 namespace
```

这个时候就可以执行 Cephfs 相关的 `unmount` 和 `mount` 操作了，实际操作完之后，发现程序写入存储正常。

问题只是临时解决了，保证业务可用和数据落盘，但是并没有找到根本原因，后续还要继续跟踪一下，倾向于怀疑 Ceph 本身的连接 Bug。因为对 Ceph 本身不太熟悉，结果可能还是无疾而终，优先保证服务可用吧。

**Comment by opskumu** [comment]
## 2020-05-04~10

### grep 和 dd 配合过滤大文件

```
dd if=file bs=1024k skip=12g | grep something
```

> https://serverfault.com/questions/829593/grep-in-a-huge-log-file-14-gb-only-the-last-x-gb

**Comment by opskumu** [comment]
## 2020-05-11~17

![image](https://user-images.githubusercontent.com/5445356/81764445-2caa7d80-9504-11ea-8efb-b2726650f6eb.png)

> https://developers.redhat.com/blog/2020/05/11/top-10-must-know-kubernetes-design-patterns/

**Comment by opskumu** [comment]
## 2020-05-18~24

**Comment by opskumu** [comment]
## 2020-05-25~31

![image](https://user-images.githubusercontent.com/5445356/82786475-44d0b400-9e97-11ea-9ac7-a52ceb19d14e.png)

> https://aws.amazon.com/cn/blogs/china/kata-containers-1-5-firecracker-support/ 有意思的结合，解决容器原生的资源隔离问题

**Comment by opskumu** [comment]
## 2020-06-01~07

### gunicorn docker 中配置优化

https://pythonspeed.com/articles/gunicorn-in-docker/

**Comment by opskumu** [comment]
## 2020-06-08~14

### Inside of Kubernetes Controller

应该是我看到的关于 Kubernetes 底层信息最详细的一篇 PPT 了，图文并茂，非常详细：

[Inside_of_Kubernetes_Controller.pdf](https://github.com/opskumu/issues/files/4750654/Inside_of_Kubernetes_Controller.pdf)

**Comment by opskumu** [comment]
## 2020-06-15~21

### scheduling-framework-extensions

![image](https://user-images.githubusercontent.com/5445356/84633725-64ea1500-af23-11ea-99ee-93722b299fb3.png)

> https://kubernetes.io/docs/concepts/scheduling-eviction/scheduling-framework/#extension-points

**Comment by opskumu** [comment]
## 2020-06-22~28

### 为什么容器中 kill -9 (SIGKILL) PID 为 1 的进程杀不掉？

容器中的 PID 为 1 的进程，如果对 SIGTERM 信号有处理，那么正常 kill -15 就可以杀死应用了，但是 kill -9 你是绝对杀死不了了，本身 SIGKILL 的信号也是捕捉不了的。那么为啥针对正常信号只要捕捉就可以成功 kill，-9 这种必杀技为啥杀不死呢。答案其实也很简单，因为 Linux 针对 PID 为 1 的进程也就是 init 进程有额外的保护，会自动忽略不会处理的信号，在容器中执行 -9 kill PID 为 1 的进程是杀不死的，这就是 PID 为 1 的主角光环。

**Comment by opskumu** [comment]
## 2020-06-29~07-05

### Linux load 负载过高，但是 CPU、IO 都很低，这个时候如何排查？

正常情况下，如果 load 过高一般从 CPU 或者 IO 入手，查看是哪些异常的应用导致的。但是今天遇到了一个奇怪的问题，线上一批服务器 load 突然告警，但是 top、vmstat、iostat 显示一切正常，CPU 使用 和 IO 并没有任何异常。出现问题一般先要排查下期间有没有什么操作，有同事期间重启了一台主机。突然一想会不会和 NFS 有关，因为相关的几个节点都挂载了这个 NFS 目录，重启的节点刚好是一个 NFS Server，再基本的操作查询无果后，问题节点启动后，load 值异常恢复。基本上确认无误了，因为其它几个节点和对应节点唯一的关系就是 NFS 了。

本地两个节点测试验证，一台启动一个 NFS Server，另外一台挂载，然后关闭 NFS Server，客户端批量启动 `tail -f </path/to/nfs/file>` 批量访问 NFS 对应文件，发现 load 值飙升，系统 CPU 和 IO 占用和之前线上现象一致都很低。

![image](https://user-images.githubusercontent.com/5445356/85993889-94bc1100-ba29-11ea-8a13-50cc1c854a37.png)

于是我想在知道原因的时候很好模拟现象，但是 load 值除了 CPU、IO 这类有关系之外还和什么有关联呢？假如再出现类似的情况如何排查问题根源？后来获取到这个解释：

> The high load can also be caused by a few factors:
>
> processes in "uninterruptible sleep" (D in the process list), that's processes waiting for some I/O.
> hardware issues, causing the system to wait for something (can be I/O).
> Please check your process list (ps auxf), for any processes which may be in D state, or look weird.
>  https://serverfault.com/questions/232289/high-load-low-io-low-cpu-usage

通过 ps aux 过滤发现果然之前批量启动的 tail 进程状态都是 `D`

![image](https://user-images.githubusercontent.com/5445356/85994598-9a662680-ba2a-11ea-87dc-d88b663c39cb.png)

> D state code means that process is in uninterruptible sleep, and that may mean different things but it is usually I/O. lockd is in-kernel daemon that manages NFS locking. You problem indeed needs more debugging, but overall it seems to be in NFS communication.
> https://unix.stackexchange.com/questions/16738/when-a-process-will-go-to-d-state

**Comment by opskumu** [comment]
## 2020-07-06~12

### 关于 K8s 组件升级顺序问题

之前有提到 K8s 组件的升级顺序，https://github.com/opskumu/issues/issues/26#issuecomment-618250072，但是实际升级过程中还是发现了一些问题，kubernetes 1.12.x 升级到 1.13.x 的时候，先升级 kubelet，测试的时候发现 kubelet 启动容器失败。遇到的问题和 https://github.com/kubernetes/kubernetes/issues/71749 一样，相关人员也回复了此问题，建议的做法是：

> kubelet must not be newer than kube-apiserver
> 
> be sure to upgrade kube-apiserver to 1.13 before upgrading kubelet
> https://github.com/kubernetes/kubernetes/issues/71749#issuecomment-445057546

**Comment by opskumu** [comment]
## 2020-07-13~19

<nil>

**Comment by opskumu** [comment]
## 2020-07-21~26

**Comment by opskumu** [comment]
##  2020-07-27~08-02

### go mod 私有仓库

https://github.com/opskumu/issues/issues/26#issuecomment-600405512 之前有记录过适用 go get 下载私有仓库的方式。go mod 中如果有私有仓库的依赖，针对 http 的私有库首先需要手动 go get 下载相关依赖，否则默认 build 操作的时候，go get 会自动以 https 的方式下载，导致下载失败。

**Comment by opskumu** [comment]
## 2020-08-03~09

**Comment by opskumu** [comment]
## 2020-08-10~08-16

##  labels、matchLabels

我们都知道 K8s 中资源的关联都是通过 label 去关联的，我们创建一个 Deployment 的时候会发现至少有三处需要填写 label 相关的信息，如：

``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:  # Deployment 本身的 label
    app: test
  name: test-v1
spec:
  replicas: 1
  selector:
    matchLabels:  # 匹配 pod 的 label
      app: test
  template:
    metadata:
      labels:  # 创建的 pod 的 label
        app: test
        version: v1
......
```

那么问题来了，我们如果创建同样的 matchLabels Deployment，如：

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
        version: v2
``` 
test-v1 和 test-v2 使用同样的 matchLabels `app:test` 匹配 pod，那么会不会出现冲突呢？答案是否定的，Deployment 比较特殊，我们如果创建一个 Service，如：

``` yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test
  name: test
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: test
  sessionAffinity: None
  type: ClusterIP
```

我们查看 Service 对应的 Endpoint 会发现是 2 个，这是我们希望看到的结果，但是同样的 matchLabels 为何没有出现两个Deployment 使用同样的 pod 呢？因为其实 Deployment 本身并不是直接创建 Pod 的，它需要创建对应的 ReplicaSet，而不同 Deployment 对应的 ReplicaSet 其实是不同的，ReplicaSet 会在原有的 matchLabels 基础上追加 labels，这也就是为什么相同 matchLabels 的 Deployment 可以和平共处的原因：

``` yaml
apiVersion: apps/v1
kind: ReplicaSet
metadata:
......
  labels:
    app: busybox
    pod-template-hash: 796d7d684f
    version: v1
......
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
      pod-template-hash: 796d7d684f
......
```

> https://medium.com/@zwhitchcox/matchlabels-labels-and-selectors-explained-in-detail-for-beginners

**Comment by opskumu** [comment]
## 2020-08-24~30

### kubectl rollout

```
# kubectl rollout --help
Manage the rollout of a resource.

 Valid resource types include:

  *  deployments
  *  daemonsets
  *  statefulsets

Examples:
  # Rollback to the previous deployment
  kubectl rollout undo deployment/abc

  # Check the rollout status of a daemonset
  kubectl rollout status daemonset/foo

Available Commands:
  history     View rollout history
  pause       Mark the provided resource as paused
  restart     Restart a resource
  resume      Resume a paused resource
  status      Show the status of the rollout
  undo        Undo a previous rollout

Usage:
  kubectl rollout SUBCOMMAND [options]

Use "kubectl <command> --help" for more information about a given command.
Use "kubectl options" for a list of global command-line options (applies to all commands).
```

**Comment by opskumu** [comment]
## 2020-09-14~20

### Kubernetes 环境变量设置注意点

在 K8s 配置容器环境变量的语法格式是这样设置的，以下为官方实例：

```
apiVersion: v1
kind: Pod
metadata:
  name: dependent-envars-demo
spec:
  containers:
    - name: dependent-envars-demo
      args:
        - while true; do echo -en '\n'; printf UNCHANGED_REFERENCE=$UNCHANGED_REFERENCE'\n'; printf SERVICE_ADDRESS=$SERVICE_ADDRESS'\n';printf ESCAPED_REFERENCE=$ESCAPED_REFERENCE'\n'; sleep 30; done;
      command:
        - sh
        - -c
      image: busybox
      env:
        - name: SERVICE_PORT
          value: "80"
        - name: SERVICE_IP
          value: "172.17.0.1"
        - name: UNCHANGED_REFERENCE
          value: "$(PROTOCOL)://$(SERVICE_IP):$(SERVICE_PORT)"
        - name: PROTOCOL
          value: "https"
        - name: SERVICE_ADDRESS
          value: "$(PROTOCOL)://$(SERVICE_IP):$(SERVICE_PORT)"
        - name: ESCAPED_REFERENCE
          value: "$$(PROTOCOL)://$(SERVICE_IP):$(SERVICE_PORT)"
```

涉及到变量的语法是通过 `$(变量名)` 来配置的，不支持我们常规 Linux 设置环境变量 `$变量名` 或者 `${变量名}` 来配置。官方示例输出实际的环境变量为：

```
UNCHANGED_REFERENCE=$(PROTOCOL)://172.17.0.1:80
SERVICE_ADDRESS=https://172.17.0.1:80
ESCAPED_REFERENCE=$(PROTOCOL)://172.17.0.1:80
```

我们可以发现环境变量其实是有先后顺序的，`UNCHANGED_REFERENCE` 定义的时候 `PROTOCOL` 还没有设置，因此 `UNCHANGED_REFERENCE` 还是原始值，并没有变动。`$$` 可以转义 `$`，实际最后输出为 `$`。另外还要注意一个坑就是，所有的变量设置都必须基于当前的值设置，比如镜像自带的环境变量 `PATH`，如果你需要依赖 `PATH`，那么直接 `$(PATH)` 是不可以的，你需要先添加 `PATH` 对应完整的路径，再在后面调用它。

**Comment by opskumu** [comment]
## 2020-09-21~27

### 节点失败时，Deployment 的工作机制

![image](https://user-images.githubusercontent.com/5445356/93865152-844dc680-fcf8-11ea-9693-16297f8fc8c7.png)

> https://medium.com/tailwinds-navigator/kubernetes-tip-how-statefulsets-behave-differently-than-deployments-when-node-fails-d29e36bca7d5

**Comment by opskumu** [comment]
## 2020-10-12~18

### Go 5 分钟之前的时间戳

```go
before, _ := time.ParseDuration("-5m")
ts := time.Now().Add(before).Unix()
```

**Comment by opskumu** [comment]
## 2020-10-26~31

### Docker 配置备忘

```
{
    "exec-opts": ["native.cgroupdriver=systemd"],
    "bip": "169.254.0.1/24",
    "live-restore": true,
    "log-driver": "json-file",
    "log-opts": {
        "max-size": "200m",
        "max-file": "5"
    },
    "init": true,
    "data-root": "/data/docker-ce",
    "insecure-registries": [
        ""
    ],
    "log-level": "warn",
    "registry-mirrors": [
        "https://docker.mirrors.ustc.edu.cn/"
    ]
}
```

**Comment by opskumu** [comment]
## 2020-11-02~08

### Kubernetes 网络策略

基本的网络策略可以参考 https://github.com/ahmetb/kubernetes-network-policy-recipes 配置。针对一些高级的或者说定制化比较强的则需要自行编写，了解 https://kubernetes.io/docs/concepts/services-networking/network-policies/ 配置原理比较重要，建议官方文档过一遍。比如，有个需求，指定空间内的 Pod 之间可以互相访问，但是访问外部空间的服务不能访问，这时候需要使用 Egress 策略，如下：

```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: deny-egress-to-other-namespaces
spec:
  podSelector:
    matchLabels:
  policyTypes:
  - Egress
  egress:
  - ports:
      - port: 53
        protocol: UDP
      - port: 53
        protocol: TCP
  - to:
      - podSelector:
          matchLabels:
```
