### ISSUE TITLE
学习周报「2022」

### ISSUE THREAD

**Issue by opskumu** [opskumu/issues#30]
2022 占个位

**Comment by opskumu** [comment]
## 04-18~24

### CPU 隔离

SUSE 官方一系列关于 CPU 隔离的文章，推荐阅读，包括 isolcpus 和 cpuset 相关都有说明

* https://www.suse.com/c/cpu-isolation-introduction-part-1/
* https://www.infoq.cn/profile/64FBB2FD98C7EE/publish 「中文翻译版本」
* https://documentation.suse.com/sle-rt/15-SP1/html/SLE-RT-all/book-slert-shielding.html

**Comment by opskumu** [comment]
## curl 通过 serviceaccount token 访问 apiserver

* https://support.huaweicloud.com/basics-cce/kubernetes_0033.html

```yaml
$ kubectl exec -it sa-example -- /bin/sh 
# export CURL_CA_BUNDLE=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
# TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
# curl -H "Authorization: Bearer $TOKEN" https://kubernetes/api/v1/namespaces/default/pods
{
  "kind": "PodList",
  "apiVersion": "v1",
  "metadata": {
    "selfLink": "/api/v1/namespaces/default/pods",
    "resourceVersion": "10377013"
  },
  "items": [
    {
      "metadata": {
        "name": "sa-example",
        "namespace": "default",
        "selfLink": "/api/v1/namespaces/default/pods/sa-example",
        "uid": "c969fb72-ad72-4111-a9f1-0a8b148e4a3f",
        "resourceVersion": "10362903",
        "creationTimestamp": "2020-07-15T06:19:26Z"
      },
      "spec": {
...
```

更快捷的方式

```
token=`kubectl get secret <secret>  -o yaml  -n <namespace> |grep "token:" |awk '{print $2}'|base64 -d`
curl -k -H "Authorization: Bearer $token"  https://127.0.0.1:8443/api/v1/pods
```
